/** Agent-authored problems. Labels come from the index, not from these topic words. */
const TOPICS: Record<string, readonly [string, string, string, string]> = {
	"C and C++": [
		"a dangling pointer returned from a function",
		"RAII and exception-safe resource ownership",
		"um ponteiro que continua sendo usado após liberar a memória",
		"a escolha entre referências, ponteiros e valores",
	],
	"C#": [
		"cancellation and exception propagation in async tasks",
		"nullable reference types and pattern matching",
		"o descarte de recursos com using e IDisposable",
		"a inferência de tipos e restrições de generics",
	],
	Go: [
		"a goroutine that stays blocked after its caller exits",
		"slice capacity and shared backing arrays",
		"o encerramento de goroutines com canais e context",
		"a diferença entre interfaces e tipos concretos",
	],
	Java: [
		"visibility of writes between threads",
		"generic type erasure and wildcard bounds",
		"o comportamento de equals e hashCode em coleções",
		"a propagação de exceções em operações assíncronas",
	],
	JavaScript: [
		"this binding in callbacks passed to another object",
		"the ordering of promise callbacks and synchronous statements",
		"a diferença entre copiar um objeto e compartilhar sua referência",
		"o escopo de variáveis capturadas por funções",
	],
	PHP: [
		"strict scalar types and unexpected implicit conversions",
		"typed properties that have not been initialized",
		"o tratamento de exceções e a liberação de recursos",
		"a diferença entre arrays associativos e objetos",
	],
	Python: [
		"a mutable default argument shared between calls",
		"iterators that can only be consumed once",
		"a captura de variáveis em funções criadas dentro de um laço",
		"o gerenciamento de arquivos com context managers",
	],
	Ruby: [
		"method lookup through included modules",
		"blocks, procs and lambdas with different return behavior",
		"o compartilhamento de objetos mutáveis entre chamadas",
		"a resolução de métodos com módulos e herança",
	],
	Rust: [
		"an iterator that holds a borrow longer than intended",
		"Send and Sync bounds when moving data between threads",
		"a transferência de ownership ao passar um valor para uma função",
		"o uso de Result para propagar erros sem panic",
	],
	TypeScript: [
		"a discriminated union that loses narrowing after assignment",
		"generic constraints that preserve the caller's result type",
		"a diferença entre unknown e tipos que permitem qualquer operação",
		"a inferência de tipos em tuplas e objetos imutáveis",
	],
	"Algorithm Design and Analysis": [
		"selecting the smallest k elements without sorting everything",
		"a graph traversal that revisits the same vertices indefinitely",
		"a análise de tempo e espaço de uma solução recursiva",
		"a escolha de uma estrutura para buscas e atualizações ordenadas",
	],
	"Architecture Boundaries": [
		"a domain service that imports a database driver",
		"dependency inversion between business rules and adapters",
		"os contratos entre domínio e infraestrutura",
		"uma dependência circular entre módulos de negócio",
	],
	"Architecture Styles": [
		"choosing modular boundaries before distributing services",
		"trade-offs between layered and event-driven systems",
		"a escolha entre monólito modular e serviços independentes",
		"os custos de comunicação de uma arquitetura distribuída",
	],
	"Distributed Architecture Decisions": [
		"handling partial failures across service boundaries",
		"consistency trade-offs when two services update related state",
		"as consequências de uma decisão de consistência eventual",
		"a escolha entre chamadas síncronas e eventos de domínio",
	],
	"Documenting Software Architecture": [
		"a component diagram that hides ownership boundaries",
		"an ADR explaining rejected design alternatives",
		"a documentação de responsabilidades e dependências de componentes",
		"a descrição de cenários de qualidade para uma decisão arquitetural",
	],
	"Domain-Driven Design": [
		"an aggregate that requires transactions across unrelated domains",
		"separating entities from value objects in a billing domain",
		"a definição de uma linguagem comum para especialistas e desenvolvedores",
		"a separação de contextos de negócio com modelos diferentes",
	],
	"Enterprise Application Architecture Patterns": [
		"choosing transaction script versus domain model",
		"mapping domain objects without leaking persistence details",
		"a separação entre serviço de aplicação e regra de domínio",
		"o controle de transações na camada de aplicação",
	],
	"Managing Software Complexity": [
		"a module whose public interface exposes too many implementation details",
		"reducing coupling without creating unnecessary abstractions",
		"a divisão de responsabilidades de um módulo difícil de entender",
		"o custo de abstrações que não escondem complexidade",
	],
	"Messaging and Integration Patterns": [
		"a message consumer that receives duplicates and out-of-order events",
		"correlation IDs across asynchronous request and reply",
		"o tratamento de mensagens que não podem ser processadas",
		"a composição de roteadores e filtros de mensagens",
	],
	"Microfrontend Architecture": [
		"independent UI teams sharing navigation and authentication contracts",
		"version skew between a shell and remotely loaded modules",
		"a definição de fronteiras entre módulos de interface independentes",
		"a troca de dados entre microfrontends sem acoplamento excessivo",
	],
	"Object-Oriented Design Patterns": [
		"replacing a large mode switch with interchangeable behaviors",
		"composing object behavior without a deep inheritance tree",
		"a escolha entre Strategy e State para comportamentos variáveis",
		"a criação de objetos sem acoplar o cliente a classes concretas",
	],
	"Object-Oriented Thinking": [
		"objects that expose mutable internals to every caller",
		"assigning behavior to the object that owns the information",
		"a distribuição de responsabilidades entre objetos colaboradores",
		"a diferença entre modelar comportamento e apenas armazenar dados",
	],
	"Reactive Systems": [
		"isolating failures while preserving responsive message handling",
		"backpressure when producers outrun consumers",
		"o isolamento de falhas entre componentes assíncronos",
		"a elasticidade de um sistema orientado a mensagens",
	],
	"Refactoring and Code Improvement": [
		"extracting a cohesive object from a class with unrelated responsibilities",
		"simplifying nested conditionals while preserving behavior",
		"a remoção de duplicação sem mudar o comportamento observável",
		"a substituição de parâmetros booleanos por operações mais claras",
	],
	"Software Architecture and Quality Attributes": [
		"turning a latency target into an architectural scenario",
		"evaluating modifiability versus runtime efficiency",
		"a definição de cenários mensuráveis de disponibilidade",
		"o impacto de decisões arquiteturais na capacidade de evolução",
	],
	"Solution Architecture": [
		"integrating existing systems under business and deployment constraints",
		"choosing component responsibilities for a complete solution",
		"o mapeamento de requisitos de negócio para componentes da solução",
		"a identificação de riscos nas integrações entre sistemas",
	],
	"The Practice of Architecting": [
		"validating a risky design assumption with a small prototype",
		"communicating architectural trade-offs to stakeholders",
		"a avaliação de alternativas antes de fixar uma arquitetura",
		"o acompanhamento de decisões arquiteturais durante a implementação",
	],
	"Writing Maintainable Code": [
		"making a function's intent clear without explanatory comments",
		"reducing hidden coupling between seemingly independent functions",
		"a organização de funções para tornar seus efeitos explícitos",
		"a simplificação de nomes e contratos de um módulo",
	],
	"Agile Testing": [
		"balancing exploratory testing with automated regression checks",
		"testing a user story before its implementation is complete",
		"a definição de uma estratégia de testes para uma entrega pequena",
		"a colaboração entre testes e desenvolvimento durante uma iteração",
	],
	ESLint: [
		"a flat configuration whose rules do not reach nested TypeScript files",
		"separating correctness checks from formatting rules",
		"uma configuração de lint que ignora arquivos por engano",
		"a aplicação de regras de qualidade sem falsos positivos",
	],
	Husky: [
		"a pre-commit hook that fails to run in a fresh clone",
		"keeping local quality hooks deterministic and fast",
		"um hook de Git que bloqueia commits com arquivos inválidos",
		"a separação entre verificações locais e verificações obrigatórias no CI",
	],
	"Istanbul and c8": [
		"branch coverage that misses the error path",
		"coverage reports that include generated files",
		"a diferença entre cobertura de linhas e de ramos",
		"a exclusão de arquivos gerados do relatório de cobertura",
	],
	Mocha: [
		"an asynchronous test that finishes before its assertion",
		"shared setup leaking state across test cases",
		"um teste assíncrono que combina callback e Promise",
		"a organização de fixtures e teardown de testes",
	],
	"Outside-In Development": [
		"driving an implementation from an acceptance example",
		"choosing collaborator contracts before internal details",
		"a implementação a partir de um teste de aceitação observável",
		"a definição de contratos de colaboradores por exemplos",
	],
	Playwright: [
		"a browser test that races against a delayed network response",
		"isolating browser storage between checkout tests",
		"um seletor de teste que quebra quando muda o texto da interface",
		"a verificação de comportamento de navegador com esperas por condições",
	],
	"Pragmatic Programming Practices": [
		"automating a repeated manual development check",
		"choosing a small reversible experiment instead of a speculative rewrite",
		"a remoção de tarefas manuais repetitivas do desenvolvimento",
		"a comunicação de riscos e estimativas com evidências",
	],
	Prettier: [
		"a formatter configuration that conflicts with editor settings",
		"keeping generated files out of formatting checks",
		"uma diferença de formatação entre o editor e o CI",
		"a aplicação consistente de formatação em arquivos de uma equipe",
	],
	"Princípios FIRST": [
		"a test that depends on external network availability",
		"a test whose outcome depends on execution order",
		"um teste lento que consulta um serviço externo",
		"a construção de testes repetíveis e capazes de verificar seu resultado",
	],
	"SOLID Design Principles": [
		"a subclass that breaks its parent's behavioral contract",
		"splitting an interface that forces clients to implement unused operations",
		"a violação do princípio de substituição em uma hierarquia de classes",
		"a inversão de dependências para isolar uma regra de negócio",
	],
	Sinon: [
		"a fake clock that is not restored after a test",
		"stubbing only the external boundary instead of every collaborator",
		"um stub que continua ativo depois de terminar um teste",
		"a distinção entre spies, stubs e mocks em testes unitários",
	],
	"Software Construction Practices": [
		"validating preconditions at a module boundary",
		"making error handling consistent across related operations",
		"a definição de invariantes para uma função de transformação",
		"a construção de código com tratamento explícito de falhas",
	],
	"Software Project Realities": [
		"replanning work after discovering an undocumented integration constraint",
		"making scope trade-offs without hiding delivery risk",
		"a revisão de uma estimativa após descobrir trabalho adicional",
		"a priorização de correções e novas funcionalidades com capacidade limitada",
	],
	"Spec-Driven Development": [
		"turning a feature specification into verifiable implementation tasks",
		"detecting contradictions before implementing a specification",
		"a transformação de uma especificação em critérios verificáveis",
		"a manutenção da relação entre requisitos e implementação",
	],
	"Specification by Example": [
		"examples that disagree about rounding at a business boundary",
		"making acceptance examples precise enough to automate",
		"a definição de exemplos concretos para uma regra de negócio ambígua",
		"a validação conjunta de critérios de aceitação por exemplos",
	],
	"Test Patterns and Smells": [
		"a test with many unrelated assertions and unclear failure messages",
		"overspecified mocks that fail after harmless refactoring",
		"um teste que verifica detalhes internos em vez do comportamento",
		"a duplicação de configuração que dificulta manter os testes",
	],
	"Test-Driven Development": [
		"implementing a new calculation through red-green-refactor steps",
		"choosing the smallest failing example for an edge case",
		"a criação de um teste que falha antes de corrigir um defeito",
		"a evolução de uma implementação por ciclos pequenos de TDD",
	],
	"Unit Testing Principles": [
		"choosing observable assertions instead of checking private calls",
		"isolating time and randomness in a deterministic unit test",
		"a avaliação do valor de um teste que replica a implementação",
		"a verificação de comportamento público com entradas de fronteira",
	],
	"Working with Legacy Code": [
		"introducing a seam before changing untested behavior",
		"writing characterization tests around a legacy dependency",
		"a criação de testes de caracterização para código sem documentação",
		"o isolamento de uma dependência antes de alterar código legado",
	],
	"Database Transactions": [
		"concurrent transactions updating the same account balance",
		"deadlocks caused by inconsistent row lock ordering",
		"o isolamento de duas transações que atualizam dados relacionados",
		"a escolha entre bloqueio pessimista e controle otimista",
	],
	"Designing Data-Intensive Systems": [
		"replication lag affecting read-after-write consistency",
		"partitioning data without creating a hot shard",
		"a consistência de leituras após gravações em réplicas",
		"a distribuição de dados entre partições com cargas diferentes",
	],
	"Dimensional Modeling": [
		"choosing the grain of a sales fact table",
		"tracking historical changes to customer dimensions",
		"a definição do grão de uma tabela de fatos de faturamento",
		"o tratamento de dimensões que mudam ao longo do tempo",
	],
	"How Databases Work Internally": [
		"write-ahead logging and crash recovery",
		"page splits and B-tree traversal during indexed lookup",
		"a recuperação de uma gravação após uma falha do processo",
		"o funcionamento de páginas e índices na estrutura de armazenamento",
	],
	"NoSQL Data Models": [
		"choosing embedded documents versus referenced entities",
		"a partition key that concentrates writes on one node",
		"a escolha de uma chave de partição para distribuir gravações",
		"a modelagem de documentos conforme os padrões de consulta",
	],
	"SQL Database Antipatterns": [
		"comma-separated values stored in a relational column",
		"an entity-attribute-value schema with unenforceable constraints",
		"um relacionamento muitos-para-muitos armazenado como texto",
		"a substituição de colunas numeradas por uma relação adequada",
	],
	"SQL Performance": [
		"a query that cannot use its index because it transforms the filtered column",
		"covering indexes and the cost of table lookups",
		"uma consulta lenta que aplica função sobre a coluna indexada",
		"a análise do plano de execução antes de criar um novo índice",
	],
	"Stream Processing": [
		"event-time windows receiving late and out-of-order records",
		"checkpoint recovery without duplicating emitted aggregates",
		"o tratamento de registros atrasados em janelas de processamento",
		"a recuperação de estado de um processador de eventos",
	],
	"Accessible Web Components": [
		"a custom dialog that traps keyboard focus incorrectly",
		"exposing a custom control's state to assistive technology",
		"o retorno de foco após fechar um diálogo",
		"a associação de nome, estado e papel a um controle web",
	],
	"Form Design and UX": [
		"field validation that hides the user's previous input",
		"helping users recover from a form submission error",
		"a apresentação de erros de validação próximos aos campos",
		"a redução de campos desnecessários em um formulário de cadastro",
	],
	"Modern CSS Layout": [
		"a flex child that refuses to shrink around long content",
		"a grid layout that must preserve readable column widths",
		"um item flexível que causa overflow com texto longo",
		"a adaptação de um layout CSS a telas pequenas",
	],
	"Practical Visual Design": [
		"a page with competing primary actions and weak visual hierarchy",
		"spacing and typography that make a dense settings panel readable",
		"a hierarquia visual de uma página com várias ações",
		"a definição de contraste e espaçamento para conteúdo denso",
	],
	"RESTful API Design": [
		"choosing resource representations and HTTP status codes",
		"idempotent retries of a resource creation request",
		"a definição de recursos, métodos HTTP e respostas de erro",
		"o contrato de paginação de uma coleção em uma API REST",
	],
	"Web Performance and Networking": [
		"large images delaying the page's largest contentful paint",
		"HTTP caching that serves stale assets after deployment",
		"a redução de requisições que bloqueiam a renderização da página",
		"o diagnóstico de latência entre DNS, conexão e resposta HTTP",
	],
	"Web Usability Principles": [
		"navigation labels that users cannot distinguish",
		"a confirmation flow that hides the consequence of an action",
		"a melhoria da navegação para encontrar uma função frequente",
		"a apresentação clara das consequências de uma ação na interface",
	],
	"WebSocket Protocol": [
		"reconnecting clients without losing message ordering",
		"a proxy closing an idle upgraded connection",
		"a manutenção de uma conexão WebSocket atrás de um proxy",
		"a distinção entre mensagens de aplicação e controle do protocolo",
	],
	AWS: [
		"deploying a service behind a load balancer with health checks",
		"a cloud service that cannot reach a private subnet",
		"a definição de rede e balanceamento para um serviço na AWS",
		"o diagnóstico de conectividade entre recursos em sub-redes distintas",
	],
	Azure: [
		"deploying an application with managed infrastructure dependencies",
		"diagnosing a failing application health probe",
		"a implantação de um serviço com recursos gerenciados no Azure",
		"o acompanhamento de métricas e falhas de uma aplicação na nuvem",
	],
	"Container Orchestration": [
		"a Kubernetes pod restarting because its readiness and liveness probes conflict",
		"resource requests, limits and scheduling pressure",
		"a configuração de recursos e probes de um pod Kubernetes",
		"um serviço Kubernetes que não encontra os pods esperados",
	],
	"Continuous Delivery": [
		"promoting the same immutable artifact across environments",
		"rolling back a release after a deployment health check fails",
		"a promoção do mesmo artefato entre homologação e produção",
		"a interrupção de um rollout quando aumentam as falhas",
	],
	"DevOps Culture": [
		"reducing handoff delays between development and operations",
		"shared ownership during a production incident",
		"a colaboração entre desenvolvimento e operação em um incidente",
		"a redução de filas de aprovação entre equipes",
	],
	"DevOps Principles": [
		"finding a bottleneck in the software delivery value stream",
		"reducing work in progress to improve delivery flow",
		"a identificação de gargalos no fluxo de entrega",
		"a limitação de trabalho em andamento para reduzir tempo de espera",
	],
	Docker: [
		"a container build that includes unnecessary compiler layers",
		"a container that starts locally but lacks runtime configuration",
		"a redução de camadas e arquivos de uma imagem Docker",
		"o diagnóstico de configuração e volumes de um contêiner",
	],
	"Git Version Control": [
		"recovering a commit using the reflog",
		"rebasing a topic branch without discarding a collaborator's changes",
		"a recuperação de um commit pelo reflog do Git",
		"a resolução de conflitos ao integrar uma branch de trabalho",
	],
	"Google Cloud": [
		"deploying a service with autoscaling and a predictable minimum capacity",
		"diagnosing cloud network routing between services",
		"a configuração de escalabilidade de um serviço no Google Cloud",
		"a investigação de falhas de comunicação entre serviços na nuvem",
	],
	"Linux Command-Line": [
		"a process that keeps a deleted log file open",
		"finding which service owns a listening socket",
		"a identificação de um processo que ocupa uma porta",
		"o diagnóstico de consumo de disco e arquivos abertos no Linux",
	],
	"Measuring Software Delivery": [
		"measuring lead time without confusing it with deployment frequency",
		"using change failure rate to investigate release reliability",
		"a medição do tempo entre uma alteração e sua chegada à produção",
		"a análise de taxa de falha de mudanças e tempo de recuperação",
	],
	Observability: [
		"correlating traces and metrics during a latency incident",
		"high-cardinality labels causing monitoring costs to grow",
		"a correlação de logs, métricas e traces em um incidente",
		"a escolha de métricas úteis para investigar degradação de serviço",
	],
	"Site Reliability Engineering": [
		"allocating an error budget to release decisions",
		"defining a user-visible service level indicator",
		"a definição de um indicador de confiabilidade percebida pelo usuário",
		"o uso do orçamento de erros para decidir sobre novas entregas",
	],
	"Stability Patterns": [
		"retry storms worsening an already overloaded dependency",
		"circuit breakers, timeouts and bulkheads for production services",
		"uma política de retries que amplia a sobrecarga de uma dependência",
		"o isolamento de falhas com limites de concorrência e timeouts",
	],
	"Systems Performance": [
		"distinguishing CPU saturation from time spent waiting on I/O",
		"finding the bottleneck before changing thread counts",
		"a distinção entre saturação de CPU e espera por entrada e saída",
		"a análise de filas e utilização antes de otimizar um serviço",
	],
	"Data Protection and GDPR": [
		"retention limits for personal data in application logs",
		"honoring an erasure request across derived datasets",
		"a limitação de retenção de dados pessoais em logs",
		"o atendimento de uma solicitação de exclusão de dados pessoais",
	],
	"Ontologies for Privacy": [
		"representing privacy obligations as traceable requirements",
		"detecting inconsistent privacy constraints in a requirements model",
		"a representação de obrigações de privacidade em um modelo de requisitos",
		"a identificação de conflitos entre requisitos de privacidade",
	],
	"OWASP ASVS": [
		"mapping server-side authorization checks to verification requirements",
		"choosing security verification evidence for a login flow",
		"a verificação de requisitos de segurança de uma aplicação",
		"a avaliação de controles de autenticação e autorização",
	],
	"Penetration Testing": [
		"planning an authorized assessment with explicit target scope",
		"validating a suspected vulnerability without unnecessary impact",
		"a definição de escopo de uma avaliação de segurança autorizada",
		"a coleta de evidências de uma vulnerabilidade com impacto limitado",
	],
	"Privacy Engineering": [
		"minimizing identifying fields in analytics events",
		"separating pseudonymous identifiers from personal data",
		"a minimização de dados identificáveis em eventos de telemetria",
		"a separação entre identificadores pseudônimos e dados pessoais",
	],
	"Secure and Reliable": [
		"containing the impact of a compromised service credential",
		"designing fail-safe behavior when a security dependency is unavailable",
		"a redução do impacto de uma credencial de serviço comprometida",
		"a definição de comportamento seguro quando uma verificação falha",
	],
	"Secure Code Review": [
		"a path traversal caused by joining an untrusted file name",
		"an authorization check applied after a protected object is already read",
		"uma leitura de arquivo que permite escapar do diretório autorizado",
		"uma verificação de autorização executada tarde demais",
	],
	"Security Engineering": [
		"least privilege for service-to-service credentials",
		"trust boundaries around externally supplied data",
		"a definição de privilégios mínimos para uma conta de serviço",
		"a identificação de fronteiras de confiança de um sistema",
	],
	"SSH and Tunnels": [
		"a forwarded administration port reachable by unintended clients",
		"restricting SSH keys to a specific forwarding operation",
		"um túnel SSH que expõe uma porta administrativa",
		"a restrição de uma chave SSH a operações autorizadas",
	],
	"Threat Modeling": [
		"identifying spoofing and replay threats in a reset flow",
		"enumerating assets and trust boundaries before choosing mitigations",
		"a identificação de ameaças em um fluxo de recuperação de conta",
		"a priorização de controles conforme ativos e fronteiras de confiança",
	],
	"Web Application Security": [
		"untrusted HTML reaching a browser rendering sink",
		"an API that exposes objects owned by another account",
		"a renderização de conteúdo não confiável que permite XSS",
		"a correção de acesso indevido a objetos de outra conta",
	],
	"Hermes Agent": [
		"resuming an interrupted agent workflow without replaying completed actions",
		"restricting an agent's tools for a recurring automation",
		"a retomada de uma automação de agente após uma interrupção",
		"a limitação de ferramentas disponíveis para uma automação recorrente",
	],
	"LLM Agent SDKs": [
		"passing structured results between cooperating agents",
		"persisting an agent handoff with bounded tool execution",
		"a transferência de uma tarefa entre agentes com resultados estruturados",
		"a persistência do estado de execução de um fluxo de agentes",
	],
	n8n: [
		"a webhook workflow that processes the same event twice",
		"branching an automation after an external API call fails",
		"um fluxo de webhook que recebe eventos duplicados",
		"a composição de chamadas de LLM com validação de resultados",
	],
	Angular: [
		"a signal-derived value that stops updating in a component",
		"dependency injection scopes and reactive form validation",
		"a atualização de estado derivado em um componente Angular",
		"a configuração de injeção de dependências e formulários reativos",
	],
	CDI: [
		"an ambiguous bean injection point with multiple implementations",
		"request-scoped beans referenced from an application-scoped component",
		"uma injeção ambígua entre implementações de um bean",
		"o ciclo de vida de beans em escopos diferentes",
	],
	Django: [
		"a queryset that issues one related-object query per row",
		"transaction boundaries around ORM updates",
		"um queryset que faz consultas adicionais para cada objeto",
		"a configuração de relações e carregamento antecipado no ORM",
	],
	EJB: [
		"container-managed transactions across session bean calls",
		"a timer callback that needs idempotent business behavior",
		"as transações gerenciadas pelo contêiner em session beans",
		"a configuração de timers e concorrência de um bean",
	],
	Electron: [
		"an IPC call that fails between the renderer and main process",
		"preload bridges and context isolation",
		"a comunicação entre renderer e processo principal",
		"a separação de responsabilidades entre preload e renderer",
	],
	Express: [
		"async route errors that bypass the intended error handler",
		"middleware ordering that makes a route unreachable",
		"a propagação de erros assíncronos para o middleware de erro",
		"a ordem de execução de middlewares e rotas",
	],
	FastAPI: [
		"request validation that does not match the declared response model",
		"dependency lifetimes across asynchronous route handlers",
		"a validação de parâmetros e modelos de resposta",
		"o ciclo de vida de dependências em rotas assíncronas",
	],
	Fastify: [
		"plugin encapsulation hiding a decorator from a route",
		"schema validation and serialization in a route plugin",
		"um decorator que não fica disponível no escopo de uma rota",
		"a validação de entrada com schemas em plugins de rota",
	],
	Flask: [
		"an application context accessed outside a request",
		"blueprint registration and configuration in an application factory",
		"o acesso ao contexto de aplicação fora de uma requisição",
		"a organização de blueprints em uma application factory",
	],
	Flutter: [
		"a widget losing state when its key changes",
		"rebuild boundaries around an expensive widget subtree",
		"a preservação de estado quando muda a chave de um widget",
		"a redução de reconstruções desnecessárias de uma árvore de widgets",
	],
	GraphQL: [
		"resolvers that create repeated database lookups",
		"a schema change that breaks existing client queries",
		"a execução de resolvers que provoca consultas repetidas",
		"a evolução de um schema sem quebrar consultas existentes",
	],
	Gulp: [
		"a task completing before its stream has finished",
		"composing parallel tasks with a final sequential packaging step",
		"uma tarefa que termina antes de concluir seu stream",
		"a composição de tarefas paralelas e sequenciais",
	],
	JPA: [
		"lazy associations accessed after the persistence context closes",
		"entity changes that are not flushed at the expected boundary",
		"uma associação lazy acessada fora do contexto de persistência",
		"o acompanhamento de alterações de entidades e operações de flush",
	],
	MapStruct: [
		"an unmapped target property in a nested DTO conversion",
		"choosing explicit mappings for differently named fields",
		"uma propriedade de destino sem mapeamento em um DTO",
		"a conversão de campos aninhados com nomes diferentes",
	],
	NestJS: [
		"a provider missing from the module that consumes it",
		"request-scoped dependencies propagating through a service graph",
		"um provider que não está disponível no módulo consumidor",
		"a propagação de escopos de dependências entre serviços",
	],
	"Next.js": [
		"a server component importing a client-only hook",
		"cache invalidation after a server-side mutation",
		"a importação de um hook de cliente em um Server Component",
		"a invalidação de cache após uma alteração no servidor",
	],
	"Node.js": [
		"stream backpressure when writing to a slow destination",
		"a process kept alive by an unreleased timer handle",
		"o controle de fluxo ao gravar em um stream lento",
		"um processo que não termina por manter handles ativos",
	],
	PrimeFaces: [
		"an AJAX update targeting the wrong component naming container",
		"view state and component validation during a partial submit",
		"uma atualização AJAX que não encontra o componente esperado",
		"a validação de componentes durante um envio parcial",
	],
	Quarkus: [
		"build-time injection discovery missing an application bean",
		"configuration differences between development and packaged execution",
		"um bean não descoberto durante a análise de build",
		"a configuração de perfis de execução da aplicação",
	],
	"React Native": [
		"a virtualized list rerendering every visible row",
		"navigation state that is lost after a screen remounts",
		"uma lista virtualizada que renderiza linhas desnecessariamente",
		"a preservação de estado ao navegar entre telas",
	],
	React: [
		"a hook effect that repeatedly resubscribes because a dependency changes identity",
		"component reconciliation with unstable list keys",
		"um effect que refaz sua assinatura a cada renderização",
		"a escolha de chaves estáveis para elementos de uma lista",
	],
	"Ruby on Rails": [
		"active record callbacks triggering unintended extra writes",
		"eager loading associations used by a controller view",
		"callbacks de persistência que causam gravações adicionais",
		"o carregamento antecipado de associações usadas em uma view",
	],
	"Spring Boot": [
		"a transactional method called through self-invocation",
		"conditional bean configuration selecting the wrong implementation",
		"um método transacional chamado sem passar pelo proxy",
		"a seleção de beans conforme propriedades de configuração",
	],
	Svelte: [
		"derived reactive state that should not be mutated directly",
		"sharing state through component context",
		"um estado derivado que está sendo alterado diretamente",
		"o compartilhamento de estado pelo contexto de componentes",
	],
	Swift: [
		"view identity causing local UI state to reset",
		"state ownership between a parent view and a child binding",
		"a identidade de uma view que faz seu estado ser reiniciado",
		"a propriedade de estado e bindings entre views SwiftUI",
	],
	Vue: [
		"a computed value that stops reacting after destructuring",
		"watcher cleanup when a component unmounts",
		"um valor computado que perde reatividade após desestruturação",
		"a limpeza de watchers ao desmontar um componente",
	],
	WebSphere: [
		"classloader isolation between deployed enterprise applications",
		"a datasource connection pool exhausted under load",
		"o isolamento de classloaders entre aplicações implantadas",
		"um pool de conexões de datasource esgotado sob carga",
	],
};

const CONSTRAINTS = [
	["Keep the example independent of application code.", "Mantenha o exemplo independente do código da aplicação."],
	["Show the smallest reproducer and its expected behavior.", "Mostre a menor reprodução e o comportamento esperado."],
	["Include the failure path as well as the successful path.", "Inclua o caminho de falha e o caminho de sucesso."],
	[
		"Explain which assumption must hold for the solution to work.",
		"Explique qual premissa é necessária para a solução funcionar.",
	],
	[
		"Compare two alternatives under a strict latency constraint.",
		"Compare duas alternativas com uma restrição de latência.",
	],
	[
		"Identify the observable evidence needed to verify the change.",
		"Identifique a evidência observável necessária para verificar a mudança.",
	],
	["Avoid depending on an external service in the example.", "Evite depender de um serviço externo no exemplo."],
	[
		"Explain the effect when two operations happen concurrently.",
		"Explique o efeito quando duas operações acontecem simultaneamente.",
	],
	["Include the trade-off when the input volume grows.", "Inclua a consequência de aumentar o volume de entrada."],
	[
		"Describe the migration from an existing implementation.",
		"Descreva a migração a partir de uma implementação existente.",
	],
] as const;

export function libraryScenario(subject: string, variant: number): { request: string; language: "en" | "pt" } {
	const topics = Object.entries(TOPICS)
		.sort(([left], [right]) => right.length - left.length)
		.find(([prefix]) => subject.startsWith(prefix))?.[1];
	if (!topics) throw new Error(`No authored training scenarios for guide ${subject}`);
	const slot = variant % 6;
	const language = slot >= 4 ? "pt" : "en";
	const request = [
		`Explain ${topics[0]} using ${subject}.`,
		`Build a minimal example of ${topics[1]} using ${subject}.`,
		`Investigate ${topics[0]} in an existing implementation using ${subject}; show how to reproduce the behavior.`,
		`Review ${topics[1]} in a project using ${subject}; identify incorrect assumptions and propose a correction.`,
		`Como resolver ${topics[2]} usando ${subject}? Mostre um exemplo concreto.`,
		`Revise ${topics[3]} em um projeto que usa ${subject}; explique a causa de um erro comum e a solução.`,
	][slot];
	const round = Math.floor(variant / 6);
	return {
		request:
			round === 0
				? request
				: `${request} ${CONSTRAINTS[(round - 1) % CONSTRAINTS.length][language === "pt" ? 1 : 0]}`,
		language,
	};
}
