import type { LibraryCategoryId } from "./questions.ts";

/** Independently authored training requests: fourteen English and six Portuguese per category. */
export const LIBRARY_SHORT_REQUESTS: Record<LibraryCategoryId, readonly string[]> = {
	languages: [
		"Explain the lifetime of a local variable captured by a JavaScript callback.",
		"Why does await pause one async function while the rest of JavaScript keeps running?",
		"Show the order of synchronous statements, resolved promises and scheduled callbacks in JavaScript.",
		"Compare JavaScript let and var when functions are created inside a loop.",
		"Explain Python yield and the state retained between successive generator calls.",
		"Why does Python reuse the same list when it is a default function argument?",
		"Explain how Go sends a value through a channel and what closing the channel means.",
		"Why does appending to a Go slice sometimes change the original array?",
		"Show which Rust borrow prevents modifying a value while a reference is still used.",
		"Explain the difference between moving and cloning a Rust String.",
		"Explain Java volatile visibility without assuming that increment becomes atomic.",
		"How does TypeScript narrow a tagged union after checking its discriminant?",
		"Explain C++ object lifetime when a temporary is bound to a reference.",
		"A React callback reads a JavaScript variable from an enclosing scope. Explain lexical capture; leave the component lifecycle unchanged.",
		"Explique a ordem das filas de callbacks e promises no runtime JavaScript.",
		"Por que uma função Python com yield lembra onde parou entre duas chamadas?",
		"Explique o que acontece ao enviar e receber valores por canais em Go.",
		"Como o Rust decide quando termina um empréstimo de uma referência?",
		"Explique o narrowing de uma união discriminada em TypeScript após um teste de tipo.",
		"Uma rota Express guarda callbacks criados em um laço. Explique o escopo de let e var no JavaScript, sem mudar o roteador.",
	],
	algorithms: [
		"Explain how depth-first traversal marks vertices to avoid visiting them repeatedly.",
		"Find a valid ordering for tasks connected by prerequisite edges.",
		"Choose an algorithm for finding a cheapest route when edge costs can be negative.",
		"Explain the invariant maintained by a minimum-priority binary heap.",
		"Compare logarithmic lookup in a balanced search tree with lookup in an unsorted array.",
		"Why does a hash table need to grow when its load factor becomes too high?",
		"Use a sliding window to find the longest substring without repeated characters.",
		"Explain the recurrence and memoization for counting ways to reach a target sum.",
		"Find the kth smallest value using partitioning instead of fully sorting the input.",
		"Explain why merge sort preserves the order of equal keys and needs auxiliary memory.",
		"Compare breadth-first and depth-first traversal on an unweighted graph.",
		"Design a trie for finding strings that share a prefix.",
		"Explain how union-find detects whether adding an edge joins two already connected sets.",
		"A React screen processes a dependency graph. Determine its topological order and detect a circular prerequisite without changing components.",
		"Explique as rotações que mantêm a altura de uma árvore AVL após uma inserção.",
		"Como identificar uma aresta de retorno durante uma busca em profundidade em um grafo?",
		"Compare o custo de inserir elementos em uma lista ordenada e em uma árvore balanceada.",
		"Explique como uma fila baseada em heap escolhe o próximo item pela prioridade.",
		"Como demonstrar o custo amortizado das operações de uma estrutura que aumenta sua capacidade?",
		"Um serviço de dados precisa consultar intervalos numéricos em memória. Escolha a estrutura de dados e analise seu custo, sem discutir o banco.",
	],
	architecture: [
		"Assign ownership of business rules to domain entities rather than transport handlers.",
		"Define a bounded context when two teams use the same term with different business meanings.",
		"Explain why an aggregate protects its invariants within one consistency boundary.",
		"Choose which bounded context publishes a business event and which contexts consume it.",
		"Document the rejected alternatives and consequences of an architecture decision.",
		"Use ports and adapters to prevent persistence details from reaching the domain.",
		"Describe component responsibilities and the direction of allowed dependencies.",
		"Choose between synchronous coordination and asynchronous domain events for a business process.",
		"Replace a family of conditional behaviors with the Strategy design pattern.",
		"Explain when the State pattern clarifies transitions of a domain object.",
		"Model a value object whose equality depends on its values rather than identity.",
		"Define contracts between independent modules in a modular monolith.",
		"Describe a quality-attribute scenario for availability and evaluate architectural alternatives.",
		"Services already run in Kubernetes. Decide their domain ownership and dependency boundaries; leave deployment manifests unchanged.",
		"Como registrar o contexto, a escolha e as consequências de uma decisão arquitetural?",
		"Defina responsabilidades e dependências permitidas entre os componentes de uma aplicação.",
		"Como separar entidades e objetos de valor em um modelo de domínio?",
		"Explique como um evento de domínio atravessa os limites de contextos de negócio.",
		"Como impedir que detalhes de persistência determinem os contratos do domínio?",
		"A API REST já tem seus recursos definidos. Modele os limites dos agregados e as responsabilidades de negócio, sem alterar URLs ou métodos HTTP.",
	],
	engineering: [
		"Write a characterization test before modifying an undocumented calculation.",
		"Remove order dependence from unit tests that share a global fixture.",
		"Choose observable assertions instead of checking a private method call.",
		"Use a fake clock to make a timer-based unit test repeatable.",
		"Explain why a passing coverage report does not prove that assertions are meaningful.",
		"Design an acceptance example that distinguishes rounding at a business boundary.",
		"Drive a small feature through failing assertion, minimum implementation and refactoring.",
		"Fix a Mocha test that reports success before its asynchronous assertion runs.",
		"Restore Sinon stubs after each test to prevent shared test state.",
		"Configure c8 so coverage excludes generated files and shows untested branches.",
		"Configure ESLint rules that catch accidental unused variables in source files.",
		"Separate fast deterministic checks from slow checks in a quality baseline.",
		"Identify a test smell caused by mocks that specify every internal interaction.",
		"A React feature works but its browser test is intermittent. Fix test isolation and assertions with Playwright; preserve component behavior.",
		"Como fazer um teste unitário verificar o erro esperado sem depender da rede?",
		"Elimine a dependência da ordem de execução entre dois testes que compartilham dados.",
		"Como distinguir spies, stubs e mocks ao verificar um comportamento?",
		"Configure verificações automáticas de qualidade para uma alteração pequena.",
		"Explique como exemplos de aceitação tornam uma regra de negócio verificável.",
		"Um adaptador SQL precisa de testes para falhas. Isole a fronteira externa e verifique seu comportamento, sem otimizar consultas.",
	],
	databases: [
		"Explain how a relational query optimizer chooses between an index scan and a table scan.",
		"Choose column order in a B-tree index for equality and range predicates.",
		"Explain how two transactions can overwrite each other's changes.",
		"Choose an isolation level for a transaction that must not observe changing query results.",
		"Explain what a database deadlock graph says about transaction lock ordering.",
		"Model facts, dimensions and slowly changing attributes in a data warehouse.",
		"Compare document embedding with references in a document database.",
		"Explain why a join multiplies rows when its key is not unique.",
		"Use an execution plan to investigate a sort that spills to disk.",
		"Define a watermark for out-of-order events in a streaming data pipeline.",
		"Explain the relationship between event time and processing time in stream aggregation.",
		"Design a transaction that transfers a balance without exposing a partial update.",
		"Normalize a data model to avoid inconsistent duplicate attributes.",
		"A React dashboard waits on a slow Postgres aggregation. Inspect its SQL execution plan and indexes; leave rendering unchanged.",
		"Como controlar a atualização concorrente de uma linha usando versões no banco?",
		"Explique como o nível de isolamento afeta as leituras de uma transação.",
		"Como lidar com um evento que chega depois do fechamento de uma janela de agregação?",
		"Modele uma dimensão de produto que preserva alterações históricas de atributos.",
		"Como um índice composto organiza seus valores e quais filtros conseguem aproveitá-lo?",
		"Uma entrega tem uma migração pronta no Git. Avalie bloqueios e consistência das transações da migração, sem mudar o histórico do repositório.",
	],
	web_frontend: [
		"Define HTTP resource representations and status codes for creating and updating an order.",
		"Design cursor pagination and error responses for a REST collection.",
		"Explain HTTP conditional requests using entity tags and preconditions.",
		"Define which HTTP methods are idempotent and how a client can safely retry them.",
		"Make an HTML form announce its invalid fields to assistive technology.",
		"Choose accessible labels and focus order for a multi-step form.",
		"Fix a CSS layout whose intrinsic minimum size prevents a grid item from shrinking.",
		"Use CSS Flexbox to align items while preserving wrapping on narrow screens.",
		"Reserve image dimensions to prevent visible layout jumps during page loading.",
		"Explain the initial HTTP negotiation for establishing a WebSocket connection.",
		"Define reconnect and heartbeat behavior for a browser WebSocket client.",
		"Improve contrast and information hierarchy in a checkout page.",
		"Make a web dialog support keyboard focus and dismissal.",
		"A Spring service exposes an HTTP interface. Define resource URLs and response semantics; leave bean configuration unchanged.",
		"Como associar mensagens de erro aos campos de um formulário HTML acessível?",
		"Ajuste o layout CSS para funcionar em telas estreitas sem rolagem horizontal.",
		"Explique como implementar paginação de uma coleção por um contrato HTTP.",
		"Como restaurar o foco do teclado quando um diálogo web é fechado?",
		"Defina códigos de resposta para conflito e falha de validação em uma API REST.",
		"Uma tela React contém campos HTML sem rótulos. Corrija as associações e os anúncios de erro com padrões da web, sem mudar hooks.",
	],
	devops: [
		"Explain the difference between merging and rebasing a Git topic branch.",
		"Move a local Git branch onto updated main while preserving its individual commits.",
		"Undo a change on a shared Git branch by adding a reversing commit.",
		"Use Git bisect to locate the commit that introduced a regression.",
		"Recover an accidentally detached commit from Git's reflog.",
		"Resolve conflict markers while applying a sequence of Git commits.",
		"Promote one immutable container artifact through staging and production.",
		"Stop a release automatically when its health checks fail and restore the previous artifact.",
		"Configure readiness checks so a Kubernetes service sends traffic only to ready pods.",
		"Choose a gradual rollout policy and operational metrics for a deployment.",
		"Define a service-level objective and a rule for spending its error budget.",
		"Investigate a production latency incident with correlated traces and metrics.",
		"Use a Docker multi-stage build to keep build dependencies out of a runtime image.",
		"A security correction is complete. Integrate its Git branch with updated main and resolve commit conflicts; preserve the corrected code.",
		"Explique como reorganizar commits locais com o rebase interativo do Git.",
		"Como desfazer uma alteração publicada criando outro commit no Git?",
		"Configure rollback de uma implantação quando as verificações de saúde falham.",
		"Como usar métricas de confiabilidade para decidir sobre a promoção de uma versão?",
		"Configure probes e limites de recursos para uma aplicação no Kubernetes.",
		"Uma aplicação React está pronta. Configure cache e promoção de artefatos no pipeline de CI, sem alterar componentes.",
	],
	security: [
		"Replace concatenated untrusted values in a SQL statement with safely bound parameters.",
		"Check object ownership before returning a record identified by a URL parameter.",
		"Prevent untrusted markup from reaching an executable browser rendering sink.",
		"Identify replay and token theft threats in an account recovery flow.",
		"Restrict an SSH key to one forwarding destination and prohibit shell access.",
		"Reduce the network exposure of an SSH-forwarded administration service.",
		"Prevent a supplied file name from escaping an authorized directory.",
		"Choose least-privilege credentials for communication between services.",
		"Define retention and erasure controls for personal data in logs.",
		"Separate pseudonymous analytics identifiers from directly identifying fields.",
		"Map authorization checks to OWASP ASVS verification requirements.",
		"Scope an authorized penetration test and define evidence collection limits.",
		"Identify trust boundaries before choosing mitigations for an upload service.",
		"A SQL query is fast but includes user-controlled text directly. Remove injection risk; leave its execution-plan optimization unchanged.",
		"Como impedir que uma rota exponha dados pertencentes a outra conta?",
		"Restrinja os destinos de encaminhamento permitidos por uma chave SSH.",
		"Explique como validar o caminho de um arquivo antes de acessar dados protegidos.",
		"Defina controles de minimização e retenção para dados pessoais de telemetria.",
		"Como verificar autorização antes de executar uma operação sobre um objeto?",
		"Uma view Django aceita uma operação autenticada por cookie. Analise proteção contra CSRF e fronteiras de confiança, sem revisar o ORM.",
	],
	automation: [
		"Configure an n8n webhook automation to persist progress between external API calls.",
		"Combine responses from several model calls in an n8n workflow.",
		"Retry transient failures in n8n without repeating completed external actions.",
		"Deduplicate incoming webhook events before an n8n automation processes them.",
		"Use an agent SDK to delegate a task and receive a structured result.",
		"Give a specialist LLM agent only the tools needed for its delegated work.",
		"Persist the handoff state of an LLM agent before starting a dependent task.",
		"Coordinate parallel agent tasks with bounded execution and explicit completion signals.",
		"Configure Hermes Agent to resume from its last completed workflow step.",
		"Limit the tool access of a recurring Hermes automation.",
		"Validate structured model output before continuing an automated workflow.",
		"Store the correlation between an agent task and its returned result.",
		"Route failed automation steps to a recovery branch in n8n.",
		"A TypeScript step uses an LLM Agent SDK. Implement task delegation and returned-result handling; leave language typing unchanged.",
		"Como persistir uma etapa concluída de uma automação n8n antes de chamar outra API?",
		"Configure retomada e tratamento de falhas de um fluxo de agentes LLM.",
		"Como limitar ferramentas disponíveis para uma tarefa delegada em um Agent SDK?",
		"Organize a validação e a combinação de respostas de modelos em uma automação n8n.",
		"Como o Hermes Agent pode retomar um fluxo sem repetir efeitos já confirmados?",
		"Um serviço Java fornece a API de uma automação n8n. Configure a orquestração e os retries no fluxo, sem mudar a implementação Java.",
	],
	frameworks: [
		"Fix a React effect whose dependency array causes repeated subscriptions.",
		"Choose stable React list keys to preserve child component state.",
		"Explain when React memoization helps and when unstable props defeat it.",
		"Separate client-only hooks from server rendering in Next.js.",
		"Invalidate a Next.js route cache after a server-side mutation.",
		"Choose Angular dependency injection scopes for a stateful service.",
		"Derive Angular component state with signals and computed values.",
		"Configure NestJS module exports so another module can inject a provider.",
		"Explain why Spring transaction advice does not apply to a self-invoked method.",
		"Select a Spring Boot bean with configuration properties and conditional annotations.",
		"Use Django select_related and prefetch_related for ORM association loading.",
		"Restore Vue reactivity after destructuring a reactive object.",
		"Share Svelte reactive state through component context.",
		"A Rust service supplies data to Next.js. Fix the Next.js server/client component boundary; leave Rust ownership rules unchanged.",
		"Como corrigir as dependências de um effect React e encerrar sua assinatura?",
		"Configure o escopo de providers e os imports de módulos no NestJS.",
		"Explique a diferença entre transações Spring chamadas pelo proxy e por self-invocation.",
		"Como carregar relações do ORM Django sem consultas adicionais por objeto?",
		"Corrija a limpeza de um watcher Vue quando seu componente é desmontado.",
		"Uma API C# atende uma tela Angular. Corrija a atualização de signals do componente Angular, sem revisar tipos C#.",
	],
};
