import type { LayaModelManifest } from "./runtime.ts";

/**
 * The trained Laya model Relay downloads on first use. Generated by `scripts/package-laya-model.mjs`;
 * do not edit by hand. The files live in the GitHub Release `laya-model-v1`.
 */
export const LAYA_MODEL_MANIFEST: LayaModelManifest = {
	version: "v1",
	layaPackage: "laya[serve]==0.3.27",
	baseUrl: "https://github.com/eltonssouza/relay-harness/releases/download/laya-model-v1/",
	files: [
		{
			path: "encoder/config.json",
			asset: "encoder__config.json",
			size: 2018,
			sha256: "d69c2320a59a1dd825838a66792048566537c845a30127d2e4fef7ccc759d938",
		},
		{
			path: "laya_trainer_meta.json",
			asset: "laya_trainer_meta.json",
			size: 904,
			sha256: "8a8970d8339248e2358a5bb0764cf02f3524f467634575774f9370d7c288c589",
		},
		{
			path: "model.safetensors",
			asset: "model.safetensors",
			size: 643835524,
			sha256: "d950dc93a2bd0fcf12b7ec1575390c3507073d0f00896adb4727b94ceef192ad",
		},
		{
			path: "rl_agent_config.json",
			asset: "rl_agent_config.json",
			size: 584,
			sha256: "1c556afd40de99c56dd3bec53fbf65120461bfe4f7900b242dcaed10e79d2fad",
		},
		{
			path: "tokenizer/tokenizer.json",
			asset: "tokenizer__tokenizer.json",
			size: 34363188,
			sha256: "609d8f4c067cd3950f88594c5a802616cea245823836ef5848ee4fc40aab5b6f",
		},
		{
			path: "tokenizer/tokenizer_config.json",
			asset: "tokenizer__tokenizer_config.json",
			size: 648,
			sha256: "5f36fa307ecb9e70c9b058ca0621530f6bd3e89b371c4d6c0279c48d9dbd2629",
		},
	],
};
