import type { LayaModelManifest } from "./runtime.ts";

/**
 * The trained Laya model baked into the Laya Docker image. Generated by `scripts/package-laya-model.mjs`;
 * do not edit by hand. The files live at `https://huggingface.co/eltonssouza/relay-laya/resolve/94cfb67024e9538729686085e1a63c26301520cb/`.
 */
export const LAYA_MODEL_MANIFEST: LayaModelManifest = {
	version: "v4-library-retry",
	layaPackage: "laya[serve]==0.3.27",
	baseUrl: "https://huggingface.co/eltonssouza/relay-laya/resolve/94cfb67024e9538729686085e1a63c26301520cb/",
	files: [
		{
			path: "encoder/config.json",
			asset: "encoder/config.json",
			size: 1939,
			sha256: "81d6856137aeb1d9cfbc1c1776d5b8196eed2e6ff879e894f517a21a580cc9d3",
		},
		{
			path: "laya_trainer_meta.json",
			asset: "laya_trainer_meta.json",
			size: 1449,
			sha256: "66dbd05e829a10af58955100b8c57b32cd09f4da975fdc4ce381fd86b9582145",
		},
		{
			path: "model.safetensors",
			asset: "model.safetensors",
			size: 643835524,
			sha256: "cd4e9af682d55fb8b4e0fd922400aa868e6778982c869c71596ed2128df80ede",
		},
		{
			path: "rl_agent_config.json",
			asset: "rl_agent_config.json",
			size: 558,
			sha256: "51382bc22263d7e56914245017e53bf78609917af739d6b307c37307869ef5f0",
		},
		{
			path: "tokenizer/tokenizer.json",
			asset: "tokenizer/tokenizer.json",
			size: 34363188,
			sha256: "609d8f4c067cd3950f88594c5a802616cea245823836ef5848ee4fc40aab5b6f",
		},
		{
			path: "tokenizer/tokenizer_config.json",
			asset: "tokenizer/tokenizer_config.json",
			size: 623,
			sha256: "e8e6a37c189f9dd23976b86b3e1ddb6928472e9f87c94103a1aaff311f45f090",
		},
	],
};
