import type { LayaModelManifest } from "./runtime.ts";

/**
 * The trained Laya model baked into the Laya Docker image. Generated by `scripts/package-laya-model.mjs`;
 * do not edit by hand. The files live at `https://huggingface.co/eltonssouza/relay-laya/resolve/a09e691d3cdc45058e5fa4eb2497ae304e20f772/`.
 */
export const LAYA_MODEL_MANIFEST: LayaModelManifest = {
	version: "v3",
	layaPackage: "laya[serve]==0.3.27",
	baseUrl: "https://huggingface.co/eltonssouza/relay-laya/resolve/a09e691d3cdc45058e5fa4eb2497ae304e20f772/",
	files: [
		{
			path: "encoder/config.json",
			asset: "encoder/config.json",
			size: 1939,
			sha256: "81d6856137aeb1d9cfbc1c1776d5b8196eed2e6ff879e894f517a21a580cc9d3",
		},
		{
			path: "laya_trainer_meta.json",
			asset: "laya_trainer_meta.json",
			size: 747,
			sha256: "a7ab5da77b8c050479d4026183b63634709b17e7d0ef3c0234cc3232ae052da7",
		},
		{
			path: "model.safetensors",
			asset: "model.safetensors",
			size: 643835524,
			sha256: "0fb72b369229774038533c359b4268cefdbbc5a504f4645b7cd2805112d922a5",
		},
		{
			path: "rl_agent_config.json",
			asset: "rl_agent_config.json",
			size: 558,
			sha256: "107825b5cd9b32b28a4c27fb495f22b51bc430919a4698ad5dddd27cf0876757",
		},
		{
			path: "tokenizer/tokenizer.json",
			asset: "tokenizer/tokenizer.json",
			size: 34363188,
			sha256: "609d8f4c067cd3950f88594c5a802616cea245823836ef5848ee4fc40aab5b6f",
		},
		{
			path: "tokenizer/tokenizer_config.json",
			asset: "tokenizer/tokenizer_config.json",
			size: 623,
			sha256: "e8e6a37c189f9dd23976b86b3e1ddb6928472e9f87c94103a1aaff311f45f090",
		},
	],
};
